### ISSUE TITLE
Missing character when searching metrics

### ISSUE THREAD

**Issue by ygmath** [MarkIannucci/ChromeUserWebSearchExtension#14]
https://userweb.epic.com/Thread/80415?repliesSince=2018-10-29T07%3a09%3a35&reply=371800

> Ah...yes...I see the same behavior.  Thanks for the clarification!  It looks like Mark coded the append of 'type=4' to the metric search, but looks like it's missing the & in the query string.  Bug it is!
> 
>  
> 
> case 'metric':
> 
> var newURL = 'https://datahandbook.epic.com/Search/Index?SearchWord=' + encodeURIComponent(trimAlligators(text.substring(6))) + 'type=4';
> 
> break;

**Comment by ima9rd** [comment]
Submitted pull request #15 to address this issue.
