### ISSUE TITLE
Sherlock search using keyword SLG

### ISSUE THREAD

**Issue by arglenn** [MarkIannucci/ChromeUserWebSearchExtension#30]
**Is your feature request related to a problem? Please describe.**
Right now I can type out Sherlock and search slgs (sherlocks), however, most of us in the Epic community know them as SLGs. 

**Describe the solution you'd like**
Make typing "uw slg" do the same as "uw sherlock"

**Comment by MarkIannucci** [comment]
Thanks for the suggestion @arglenn .  I finished the code a few minutes ago and Chrome's extension self updating functionality will update the code across the user base over the next few hours.
